### ISSUE TITLE
Bundle size as it relates to modules that are deemed impure and module aliases

### ISSUE THREAD

**Issue by arecvlohe** [reazen/relude#168] opened 2019-09-29 19:02 UTC
First off, relude is a great library. I appreciate the batteries-included approach to make it easier for me to code in the way I enjoy.

I want to bring up bundle size and tree shaking. I recently started using relude in a side project of mine and after bundling, react shows the warning that my main file exceeds the 244kb and may impact web performance. I looked in the main bundle and found things that I am not using like `Monoid`. Additionally, I come across lines in the bundle output like this:

```
x=l.MonadInfix(p),E=[y[0],y[1],y[2],y[3],y[4],y[5],b[0],b[1],b[2],b[3],x[0],x[1],x[2],x[3],x[4]];return[e,d,r[0],r[1],r[2],r[3],r[4],r[5],u,i,o[0],o[1],o[2],o[3],o[4],o[5],o[6],o[7],o[8],o[9],o[10],o[11],o[12],o[13],o[14],s,m,_[0],_[1],p,h,g[0],g[1],g[2],g[3],g[4],g[5],g[6],g[7],E]}}},f
```

I think I am using only 1 infix operator, compose. Although MonadInfix might be something totally different, but I am not sure.

All of this might be more dependent on the other relude libraries though and how they are constructed using more complex modules and thus that is what is being added to the main bundle. Not entirely sure myself but curious what your thoughts are.

The repo is: https://github.com/nativesintech/muscogee-creek-dictionary.
If you want to pull it down and then build it locally you can see the output yourself and maybe you will have a better idea from seeing the source.

Anyhow, great library and I appreciate any insight into how to make the bundle size smaller.

**Comment by andywhite37** [comment] 2019-09-29 22:04
Hey @arecvlohe - thanks for writing up the issue.  Yeah, we have become aware of this issue, and @mlms13 has opened a few tickets in bucklescript - and we're still trying to figure out what we can do to help with this problem.  Unfortunately both tickets were closed, but we are still trying to strategize on how to report a ticket that might see some more actionable work.

- https://github.com/BuckleScript/bucklescript/issues/3839
- https://github.com/BuckleScript/bucklescript/issues/3852

We think the problem is related to the fact that bucklescript is flagging modules as impure, and this impurity basically works its way up the dependency tree of modules, kind of infecting the entire library.  Then, I don't completely understand why, but impure modules are being imported by default in places where they wouldn't normally be needed, causing way bigger import lists than necessary, blowing up the package size.  We think this new behavior was introduced sometime between bs-platform 5.0.4 and 5.2.0, but I'm not sure exactly what changed and when.

It would be great to solve this problem in bucklescript, but I'm not yet sure how to ask or what would need to be done, so there is some work there.  @mlms13 has tried various tree-shaking approaches on the output .js code, but I'm not sure how fruitful that has been.

@mlms13 knows more about what's going on that I do, but I'd like to dig into the problem a little more on my own to see how it behaves.

Hopefully this will get solved in some way or another in the near future, we'll update this issue with any news.

**Comment by mlms13** [comment] 2019-09-30 15:49
Oh hey, I was chatting with @arecvlohe about this topic on Discord, and at the time I didn't even realize this issue was open. I'll summarize my findings (so far) here, for anyone following along.


### es6 vs commonjs modules

Using `es6` modules in your `bsconfig.json` is just about the only way to get function-level dead code elimination in JS. My understanding is that with `commonjs` modules, bundlers are only able to find (and potentially eliminate) unused modules, while es6 modules can be rewritten by bundlers to grab only the functions they need.

Rollup is known to be quite good at optimizing these benefits with es6 modules. I think newer versions of Webpack may as well, but I need to look into this a bit more.

### Side effects when importing

Importing a module can cause side effects to run in JS, which seems absolutely awful to me, but I guess this is the world we live in.

With Bucklescript 5.2.0, imports that appear unused in Reason (e.g. `module Foo = MyLib_Foo` where `Foo` isn't used in the module, only re-exported) [will include the `import` in the JS](https://github.com/BuckleScript/bucklescript/issues/3839) if the compiler thinks `MyLib_Foo` has side effects. While this is technically the correct thing to do, [Bucklescript seems to think first-class-module application](https://github.com/BuckleScript/bucklescript/issues/3852) causes modules to be effectful. This false positive causes libraries like bs-abstract and Relude, which make liberal use of this feature, to end up with lots of unused imports in the JS.

Rollup doesn't remove these unused imports, because they _could_ be running side effects on import. To work around this, Rollup's tree-shaking [has a configuration option](https://rollupjs.org/guide/en/#treeshake) to convince it that all module imports are pure:

```js
treeshake: {
  moduleSideEffects: false
}
```

Setting this option _could_ be risky if you depend on JS libraries that expect unused imports to be preserved for their side effects. Hopefully most libraries aren't doing that?

### Current state of things

I'm currently experimenting with bundling in this demo project: https://github.com/mlms13/csv-reader

That repository includes my current Rollup config, plus some npm scripts that combine Rollup + Terser. While my bundle is also in the 200kb range, that's the full project including React, and with gzip, it compresses to about 64kb. 

This still isn't perfect, though. The un-minified bundle is correctly exluding functions like `List.catOption` (which I'm not using), but for some reason it has things like `Functor.flap` and `List.flap`, which I'm pretty sure are also unused.

Anyway, I'll keep investigating, and I won't close this ticket until we can provide some kind of bundling guide to help people have the best possible experience, even if the answers aren't completely satisfying.

**Comment by andywhite37** [comment] 2019-10-01 04:15
https://github.com/BuckleScript/bucklescript/issues/3852 has been re-opened, and it sounds like Bob is going to try some changes, so we'll see what happens.

**Comment by TheSpyder** [comment] 2019-10-01 11:46
To clarify what I said in the BuckleScript ticket, this isn't BuckleScript behaviour; it's OCaml. Much like JS, OCaml allows impure code everywhere so _any_ reference to a module has the potential to trigger a side effect.

This is trending into the effect tracking aka pure vs impure language debate. Until we have algebraic effects it is untenable to prove any given function does not have side effects, but those are probably still years away.

It's the alias reference change that triggered this. Downgrading to `bs-platform@latest` 5.0.6 (or even 5.1.0) should restore the bundle size. In fact I'd recommend staying on `latest` at all times for most people; imo 5.1/5.2/6.x are still considered beta and in need of testing.

**Comment by andywhite37** [comment] 2019-10-01 14:42
@TheSpyder - thanks for your comment, and yes, the side effect problem makes sense.

We did downgrade our version of bs-platform at one point, but several of the most recent versions have had various problems that have made us long for fixes in newer versions:

- reason-language-server stopped working with bucklescript in 5.0.4 (https://github.com/jaredly/reason-language-server/issues/275) - prompting us to upgrade to 5.0.6
- stale builds requiring fairly frequent clean rebuilds in 5.0.6 - https://github.com/BuckleScript/bucklescript/issues/3796, prompting us to upgrade to 5.1.0
- circular dependency problems were not being reported but causing the compilation to fail (not sure what version this started maybe 5.0.6 or 5.1.0)?

**Comment by TheSpyder** [comment] 2019-10-02 07:00
RLS was fine with 5.0.6 for me, I upgraded to fix the stale build issue. I didn't realise the stale build issue was so recent, but the fix applied for it is definitely what caused this.

**Comment by bobzhang** [comment] 2019-10-02 13:57
Is it possible to use the namespace provided bsb instead of handling rolling the module aliases in `relude.re`, I think the namespace support by bsb handles this properly

The current semantics is correct by OCaml but not desired

**Comment by mlms13** [comment] 2019-10-02 14:01
> Is it possible to use the namespace provided bsb instead of handling rolling the module aliases in relude.re, I think the namespace support by bsb handles this properly

I think we ran into some problems internally with modules like `Relude_String` (which would just be `String`) shadowing the OCaml stdlib, but I don't remember the details. Also, I think at one point the Bucklescript namespacing feature didn't work with odoc... not that we've gotten odoc working with this project anyway. :P

**Comment by bobzhang** [comment] 2019-10-02 14:04
I suggest you give it a try. At the same time, we can work on some relax or allow user to customize the behavior to some extent.

>we ran into some problems internally with modules like Relude_String (which would just be String) shadowing the OCaml stdlib, but I don't remember the details.

It should be fixed, otherwise, we would like to fix it

**Comment by andywhite37** [comment] 2019-10-02 21:26
I'm renaming this issue to narrow it to just the bundle size as it relates to impure modules and module aliases.  We're looking at some other sources of bundle bloat, and we'll open different issues as we find out more.

**Comment by bobzhang** [comment] 2019-10-16 08:30
can you confirm it is fixed in master

**Comment by arecvlohe** [comment] 2019-10-18 17:22
@bobzhang Not sure what fixed in master refers to. Also, are you talking to me or @andywhite37 or @mlms13?

**Comment by mlms13** [comment] 2019-10-18 18:33
@arecvlohe my understanding is that Bucklescript has a change that will make "modules that just alias other modules" considered pure so they don't automatically import _everything_ in the compiled JS. I think this change might be in `bs-platform@5.2.1`, so one of us should try it out.

**Comment by arecvlohe** [comment] 2019-10-18 18:46
@mlms13 Cool, I will give it a try later!

**Comment by arecvlohe** [comment] 2019-10-19 06:36
Okay so I tried this tonight and my bundle size went up in my `main.js` file, from `346 KiB` to `385 KiB`. Maybe more stuff was moved in there from other files possibly. Also I see things still related to `monoid` in my `main.js` file. This is not scientific observations but it's what I am seeing. Do I need to be doing something else?

**Comment by TheSpyder** [comment] 2019-10-19 07:57
You might need to use master - npm install from the bucklescript github repo URL should work.

**Comment by arecvlohe** [comment] 2019-10-19 16:19
Hmmm @TheSpyder I change my package.json to use `"bs-platform": "BuckleScript/bucklescript#master"`. When I run my build command I get the same amount of output, `385 KiB` in my `main.js` file. Am I doing this correct?

**Comment by andywhite37** [comment] 2019-10-19 23:02
I think that's what you're supposed to do @arecvlohe - the new version of bs-platform is supposed to make modules like `Relude` that purely contain module aliases as "pure" so that the compiler doesn't implicitly have to link in all the other modules that it deems impure (which is basically everything apparently).

I'll try it out later tonight to confirm, but I think the change we'd expect from thsi is that the compile `Relude.bs.js` file should say something like `pure module` or `no side effect` at the bottom.  I'm actually not sure if this will alleviate any of the bundling problems, or if new problems have surfaced.  I'll try to look into it more tonight to see where we're at now.

**Comment by arecvlohe** [comment] 2019-10-20 02:12
@andywhite37 Thanks! So for being so elementary. Most of this stuff is beyond me right not but I am glad to help anyway I can.

**Comment by andywhite37** [comment] 2019-10-21 03:39
I just installed bs-platform 5.2.1, which contains the change to treat modules containing only module aliases as pure.  `Relude.bs.js` now has the `/* No side effect */` comment at the bottom, so I think the change is doing what it's supposed to do.

@arecvlohe - it's possible the bundle size you're seeing is coming from other sources of bundle bloat, and we are still looking into those.

**Comment by andywhite37** [comment] 2019-10-21 17:32
I'm going to close this for now, because I don't think there's any plan to do more with it at the moment.  If we find that this issue is still contributing to any other problems, we can re-open.

**Closed by andywhite37** 2019-10-21 17:32 UTC
